"""delete test_field

Revision ID: 869ebe3074ea
Revises: ce0ef7b8e72f
Create Date: 2024-01-20 20:30:52.906197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '869ebe3074ea'
down_revision: Union[str, None] = 'ce0ef7b8e72f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'test_field')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('test_field', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
