"""initial test

Revision ID: ce0ef7b8e72f
Revises: 8c257ac2ad1c
Create Date: 2024-01-20 20:29:21.173292

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce0ef7b8e72f'
down_revision: Union[str, None] = '8c257ac2ad1c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tg_user', sa.Column('test_field', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tg_user', 'test_field')
    # ### end Alembic commands ###
